id: I7D4D667B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T09:35:42+00:00'
last_modified: '2022-06-08T10:40:51.009738+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W24168
  title: གཞོན་ནུ་དྲུག་གི་རྟོགས་བརྗོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CBA5:
      image_group_id: I1CZ980
      title: ''
      total_pages: 104
      order: 1
      base_file: CBA5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
